<?php
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //


if( ! defined( 'XOOPS_ROOT_PATH' ) ) exit ;
$mydirname = basename( dirname( __FILE__ ) ) ;
//$mydirnumber = substr($mydirname, 3, 1);
$mydirnumber ='';
//Plural installation has a problem in SESSSION.

$modversion['name'] = "ZenCart On XOOPS {$mydirnumber}";
$modversion['version'] = "1.34";
$modversion['description'] = "Online shop module for XOOPS. Zen-Cart functions on your XOOPS.";
$modversion['author'] = "hira( http://www.s-page.net/ )";
$modversion['credits'] = "http://www.s-page.net/";
$modversion['license'] = "GPL";
$modversion['help'] = "";
$modversion['official'] = 0;
$modversion['image'] = "zox_files/logo{$mydirnumber}.gif";
$modversion['dirname'] = $mydirname;

//Install
//$modversion['onInstall'] ="zox_files/install_module.php";//before install
//$modversion['onUpdate'] ="zox_files/update_module.php";//before update

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/zox_install{$mydirnumber}.sql";

$array_tables = Array(
//from database_tables.php
address_book,
admin,
admin_activity_log,
address_format,
authorizenet,
banners,
banners_history,
categories,
categories_description,
configuration,
configuration_group,
counter,
counter_history,
countries,
coupon_gv_queue,
coupon_gv_customer,
coupon_email_track,
coupon_redeem_track,
coupon_restrict,
coupons,
coupons_description,
currencies,
customers,
customers_basket,
customers_basket_attributes,
customers_info,
db_cache,
email_archive,
ezpages,
featured,
files_uploaded,
group_pricing,
get_terms_to_filter,
languages,
layout_boxes,
manufacturers,
manufacturers_info,
meta_tags_products_description,
meta_tags_categories_description,
newsletters,
orders,
orders_products,
orders_products_attributes,
orders_products_download,
orders_status,
orders_status_history,
orders_total,
paypal,
paypal_session,
paypal_payment_status,
paypal_payment_status_history,
products,
product_types,
product_type_layout,
product_types_to_category,
products_attributes,
products_attributes_download,
products_description,
products_discount_quantity,
products_notifications,
products_options,
products_options_values,
products_options_values_to_products_options,
products_options_types,
products_to_categories,
project_version,
project_version_history,
query_builder,
reviews,
reviews_description,
salemaker_sales,
sessions,
specials,
template_select,
tax_class,
tax_rates,
geo_zones,
zones_to_geo_zones,
upgrade_exceptions,
customers_wishlist,
whos_online,
zones,
// from includes/extra_datafiles/music_type_database_names.php
record_artists,
record_artists_info,
record_company,
record_company_info,
product_music_extra,
music_genre,
//music_genre_info,
media_manager,
media_types,
media_clips,
media_to_products,
//other
paypal_testing,
nochex_apc_transactions,
nochex_sessions
);//array eof

for($i=0;$i<count($array_tables);$i++) {
	$modversion['tables'][$i] = "zox{$mydirnumber}_" . $array_tables[$i];
}


// Admin things
$modversion['hasAdmin']   = 1;
$modversion['adminindex'] = "admin/index.php";
//$modversion['adminmenu']  = "admin/menu.php";

// Search
$modversion['hasSearch'] = 1;
//$modversion['search']['file'] 
//$modversion['search']['func'] 

// Menu
$modversion['hasMain'] = 1;
//$modversion['sub'][1]['name'] = "Home";
//$modversion['sub'][1]['url'] = "index.php";

// Blocks

	//CSS/AJAX
		$modversion['blocks'][1]['file'] = "zox_blocks.php";
		$modversion['blocks'][1]['name'] = "CSS/AJAX{$mydirnumber}_none";
		$modversion['blocks'][1]['description'] = "read CSS and javascript of ZenCart";
		$modversion['blocks'][1]['show_func'] = "b_zox_first_block_show";
		$modversion['blocks'][1]['template'] = "zox_block.html";
		$modversion['blocks'][1]['options'] = "{$mydirname}";
	//sideboxes
		$modversion['blocks'][2]['file'] = "zox_blocks.php";
		$modversion['blocks'][2]['name'] = "LeftColumn{$mydirnumber}";
		$modversion['blocks'][2]['description'] = "Left Column of ZenCart";
		$modversion['blocks'][2]['show_func'] = "b_zox_block_show";
		$modversion['blocks'][2]['template'] = "zox_block.html";
		$modversion['blocks'][2]['options'] = "{$mydirname}|left";

		$modversion['blocks'][3]['file'] = "zox_blocks.php";
		$modversion['blocks'][3]['name'] = "RightColumn{$mydirnumber}";
		$modversion['blocks'][3]['description'] = "Right Column of ZenCart";
		$modversion['blocks'][3]['show_func'] = "b_zox_block_show";
		$modversion['blocks'][3]['template'] = "zox_block.html";
		$modversion['blocks'][3]['options'] = "{$mydirname}|right";

		$modversion['blocks'][4]['file'] = "zox_blocks.php";
		$modversion['blocks'][4]['name'] = "SingleColumn{$mydirnumber}";
		$modversion['blocks'][4]['description'] = "Single Column of ZenCart";
		$modversion['blocks'][4]['show_func'] = "b_zox_block_show";
		$modversion['blocks'][4]['template'] = "zox_block.html";
		$modversion['blocks'][4]['options'] = "{$mydirname}|single";

	//center
		$modversion['blocks'][5]['file'] = "zox_blocks.php";
		$modversion['blocks'][5]['name'] = "Whats_new{$mydirnumber}";
		$modversion['blocks'][5]['description'] = "whats_new of ZenCart";
		$modversion['blocks'][5]['show_func'] = "b_zox_block_show";
		$modversion['blocks'][5]['template'] = "zox_block.html";
		$modversion['blocks'][5]['options'] = "{$mydirname}|whats_new";

		$modversion['blocks'][6]['file'] = "zox_blocks.php";
		$modversion['blocks'][6]['name'] = "Specials{$mydirnumber}";
		$modversion['blocks'][6]['description'] = "specials of ZenCart";
		$modversion['blocks'][6]['show_func'] = "b_zox_block_show";
		$modversion['blocks'][6]['template'] = "zox_block.html";
		$modversion['blocks'][6]['options'] = "{$mydirname}|specials";

		$modversion['blocks'][7]['file'] = "zox_blocks.php";
		$modversion['blocks'][7]['name'] = "Featured{$mydirnumber}";
		$modversion['blocks'][7]['description'] = "featured of ZenCart";
		$modversion['blocks'][7]['show_func'] = "b_zox_block_show";
		$modversion['blocks'][7]['template'] = "zox_block.html";
		$modversion['blocks'][7]['options'] = "{$mydirname}|featured";


		$modversion['blocks'][8]['file'] = "zox_blocks.php";
		$modversion['blocks'][8]['name'] = "Upcoming{$mydirnumber}";
		$modversion['blocks'][8]['description'] = "upcoming of ZenCart";
		$modversion['blocks'][8]['show_func'] = "b_zox_block_show";
		$modversion['blocks'][8]['template'] = "zox_block.html";
		$modversion['blocks'][8]['options'] = "{$mydirname}|upcoming";

// Comments
$modversion['hasComments'] = 0;

// Notification
$modversion['hasNotification'] = 0;

// Fix CacheDir(It is carried out here whenever update.)
$module_handler =& xoops_gethandler('module');
$module =& $module_handler->getByDirname($mydirname);
if( is_object( $module ) ) {
	$zdb_sql_cache = XOOPS_ROOT_PATH."/modules/zox/cache";
	
	$db =& Database::getInstance() ;
	$db->query("UPDATE ".$db->prefix( "zox_configuration" )." SET configuration_value ='" . trim($zdb_sql_cache) . "' WHERE configuration_key = 'SESSION_WRITE_DIRECTORY'");
	
	global $xoopsUser;
	if (is_object($xoopsUser)) {
	  $zdb_email = $xoopsUser->getVar('email');
	  $db->query("UPDATE ".$db->prefix( "zox_configuration" )." SET configuration_value ='" . $zdb_email . "' WHERE configuration_value = 'admin@localhost'");
	  $db->query("UPDATE ".$db->prefix( "zox_admin" )." SET admin_email ='" . $zdb_email . "' WHERE admin_email = 'admin@localhost'");
	}
}
?>
